{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-05-23T10:21:50.663173Z",
     "iopub.status.busy": "2024-05-23T10:21:50.662917Z"
    },
    "id": "qfGtMLwLpCr3"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "nohup python -u -m http.server --bind localhost --directory=/storage/torchmirror/ 8000\n",
      "nohup: appending output to 'nohup.out'\n",
      "Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease\n",
      "Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 \u001b[0m\n",
      "Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease               \u001b[0m\n",
      "Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease\n",
      "Hit:5 https://deb.nodesource.com/node_16.x focal InRelease  \u001b[0m               \n",
      "Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease        \u001b[0m\n",
      "Hit:7 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease    \u001b[33m\u001b[33m\n",
      "Reading package lists... Done\u001b[33m\u001b[33m\u001b[33m\u001b[33m\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "176 packages can be upgraded. Run 'apt list --upgradable' to see them.\n",
      "Reading package lists... Done\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "python3.10 is already the newest version (3.10.14-1+focal1).\n",
      "0 upgraded, 0 newly installed, 0 to remove and 176 not upgraded.\n",
      "Reading package lists... Done\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "libpython3.10-dev is already the newest version (3.10.14-1+focal1).\n",
      "0 upgraded, 0 newly installed, 0 to remove and 176 not upgraded.\n",
      "Reading package lists... Done\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "build-essential is already the newest version (12.8ubuntu1.1).\n",
      "0 upgraded, 0 newly installed, 0 to remove and 176 not upgraded.\n",
      "Reading package lists... Done\n",
      "Building dependency tree       \n",
      "Reading state information... Done\n",
      "ffmpeg is already the newest version (7:4.2.7-0ubuntu0.1).\n",
      "0 upgraded, 0 newly installed, 0 to remove and 176 not upgraded.\n",
      "Collecting pip\n",
      "  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "Using cached pip-24.0-py3-none-any.whl (2.1 MB)\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 24.0\n",
      "    Uninstalling pip-24.0:\n",
      "      Successfully uninstalled pip-24.0\n",
      "Successfully installed pip-24.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting setuptools==69.5.1\n",
      "  Downloading setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)\n",
      "Downloading setuptools-69.5.1-py3-none-any.whl (894 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m894.6/894.6 kB\u001b[0m \u001b[31m59.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: setuptools\n",
      "  Attempting uninstall: setuptools\n",
      "    Found existing installation: setuptools 70.0.0\n",
      "    Uninstalling setuptools-70.0.0:\n",
      "      Successfully uninstalled setuptools-70.0.0\n",
      "Successfully installed setuptools-69.5.1\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://download.pytorch.org/whl/cu121\n",
      "Requirement already satisfied: torch==2.1.2 in /usr/local/lib/python3.10/dist-packages (2.1.2+cu121)\n",
      "Requirement already satisfied: torchvision==0.16.2 in /usr/local/lib/python3.10/dist-packages (0.16.2+cu121)\n",
      "Requirement already satisfied: torchaudio==2.1.2 in /usr/local/lib/python3.10/dist-packages (2.1.2+cu121)\n",
      "Requirement already satisfied: torchdata==0.7.1 in /usr/local/lib/python3.10/dist-packages (0.7.1)\n",
      "Requirement already satisfied: torchtext==0.16.2+cpu in /usr/local/lib/python3.10/dist-packages (0.16.2+cpu)\n",
      "Requirement already satisfied: xformers==0.0.23.post1 in /usr/local/lib/python3.10/dist-packages (0.0.23.post1)\n",
      "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (4.9.0)\n",
      "Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (1.12)\n",
      "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (3.1.3)\n",
      "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (2024.2.0)\n",
      "Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.1.2) (2.1.0)\n",
      "Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision==0.16.2) (1.26.2)\n",
      "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torchvision==0.16.2) (2.28.1)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision==0.16.2) (9.5.0)\n",
      "Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.10/dist-packages (from torchdata==0.7.1) (1.26.13)\n",
      "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from torchtext==0.16.2+cpu) (4.64.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.1.2) (2.1.5)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision==0.16.2) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->torchvision==0.16.2) (2.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->torchvision==0.16.2) (2019.11.28)\n",
      "Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch==2.1.2) (1.3.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: httpx==0.24.1 in /usr/local/lib/python3.10/dist-packages (0.24.1)\n",
      "Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx==0.24.1) (2019.11.28)\n",
      "Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/lib/python3.10/dist-packages (from httpx==0.24.1) (0.15.0)\n",
      "Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx==0.24.1) (2.8)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.24.1) (1.3.1)\n",
      "Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.10/dist-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (0.12.0)\n",
      "Requirement already satisfied: anyio==3.* in /usr/local/lib/python3.10/dist-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (3.7.1)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio==3.*->httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (1.2.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: httpx==0.24.1 in /usr/local/lib/python3.10/dist-packages (0.24.1)\n",
      "Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx==0.24.1) (2019.11.28)\n",
      "Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/lib/python3.10/dist-packages (from httpx==0.24.1) (0.15.0)\n",
      "Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx==0.24.1) (2.8)\n",
      "Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.24.1) (1.3.1)\n",
      "Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.10/dist-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (0.12.0)\n",
      "Requirement already satisfied: anyio==3.* in /usr/local/lib/python3.10/dist-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (3.7.1)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio==3.*->httpcore<0.18.0,>=0.15.0->httpx==0.24.1) (1.2.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.9.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)\n",
      "Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.26.2)\n",
      "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.0)\n",
      "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.5.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.9.0.post0)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib) (1.14.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (8.24.0)\n",
      "Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython) (0.19.1)\n",
      "Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython) (0.1.7)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython) (3.0.43)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython) (2.18.0)\n",
      "Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython) (0.6.3)\n",
      "Requirement already satisfied: traitlets>=5.13.0 in /usr/local/lib/python3.10/dist-packages (from ipython) (5.14.3)\n",
      "Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython) (1.2.1)\n",
      "Requirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.10/dist-packages (from ipython) (4.9.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython) (4.9.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython) (0.8.4)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython) (0.2.13)\n",
      "Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython) (2.0.1)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython) (2.4.1)\n",
      "Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython) (0.2.2)\n",
      "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from asttokens>=2.1.0->stack-data->ipython) (1.14.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m/storage/stable-diffusion-webui-sd\n",
      "Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]\n",
      "Version: v1.8.0\n",
      "Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5\n",
      "ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.\n",
      "Launching Web UI with arguments: --xformers --enable-insecure-extension-access --share --gradio-queue\n",
      "face_yolov8n.pt: 100%|██████████████████████| 6.23M/6.23M [00:00<00:00, 153MB/s]\n",
      "face_yolov8s.pt: 100%|██████████████████████| 22.5M/22.5M [00:00<00:00, 400MB/s]\n",
      "hand_yolov8n.pt: 100%|██████████████████████| 6.24M/6.24M [00:00<00:00, 298MB/s]\n",
      "person_yolov8n-seg.pt: 100%|████████████████| 6.78M/6.78M [00:00<00:00, 270MB/s]\n",
      "person_yolov8s-seg.pt: 100%|████████████████| 23.9M/23.9M [00:00<00:00, 409MB/s]\n",
      "yolov8x-world.pt: 100%|███████████████████████| 148M/148M [00:00<00:00, 389MB/s]\n",
      "\u001b[1m[\u001b[0m-\u001b[1m]\u001b[0m ADetailer initialized. version: \u001b[1;36m24.3\u001b[0m.\u001b[1;36m0\u001b[0m, num models: \u001b[1;36m12\u001b[0m\n",
      "ControlNet preprocessor location: /storage/stable-diffusion-webui-sd/extensions/sd-webui-controlnet/annotator/downloads\n",
      "2024-05-23 10:22:28,040 - ControlNet - \u001b[0;32mINFO\u001b[0m - ControlNet v1.1.441\n",
      "2024-05-23 10:22:28,506 - ControlNet - \u001b[0;32mINFO\u001b[0m - ControlNet v1.1.441\n",
      "Loading weights [f92618cb5f] from /storage/stable-diffusion-webui-sd/models/Stable-diffusion/astranimeMIX_v1.safetensors\n",
      "Creating model from config: /storage/stable-diffusion-webui-sd/configs/v1-inference.yaml\n",
      "2024-05-23 10:22:34,610 - ControlNet - \u001b[0;32mINFO\u001b[0m - ControlNet UI callback registered.\n",
      "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
      "  warnings.warn(\n",
      "vocab.json: 100%|████████████████████████████| 961k/961k [00:00<00:00, 11.9MB/s]\n",
      "merges.txt: 100%|████████████████████████████| 525k/525k [00:00<00:00, 28.1MB/s]\n",
      "special_tokens_map.json: 100%|█████████████████| 389/389 [00:00<00:00, 3.90MB/s]\n",
      "tokenizer_config.json: 100%|███████████████████| 905/905 [00:00<00:00, 11.3MB/s]\n",
      "config.json: 100%|█████████████████████████| 4.52k/4.52k [00:00<00:00, 1.25MB/s]\n",
      "Running on local URL:  http://127.0.0.1:7860\n",
      "Running on public URL: https://d7963e0e26f45633a3.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)\n",
      "Startup time: 19.3s (prepare environment: 2.0s, import torch: 2.7s, import gradio: 0.9s, setup paths: 1.4s, initialize shared: 0.1s, other imports: 0.8s, list SD models: 0.2s, load scripts: 2.9s, initialize extra networks: 1.2s, scripts before_ui_callback: 0.2s, create ui: 5.9s, gradio launch: 1.0s).\n",
      "Loading VAE weights specified in settings: /storage/stable-diffusion-webui-sd/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors\n",
      "Applying attention optimization: xformers... done.\n",
      "Model loaded in 14.5s (load weights from disk: 5.4s, create model: 1.4s, apply weights to model: 5.1s, load VAE: 1.9s, load textual inversion embeddings: 0.3s, calculate empty prompt: 0.2s).\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# START STABLE DIFFUSION WEBUI\n",
    "# https://github.com/javacommons/paperspace-template/blob/main/webui2.ipynb\n",
    "# python -m http.server --bind localhost --directory=/storage/torchmirror/ 8000\n",
    "#!apt update\n",
    "#!apt -y install python3.10\n",
    "#!apt -y install libpython3.10-dev\n",
    "#!apt -y install build-essential\n",
    "#!apt -y install ffmpeg\n",
    "#!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10\n",
    "#!python3.10 -m pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 torchtext==0.15.2 torchdata==0.6.1 --extra-index-url https://download.pytorch.org/whl/cu118 -U\n",
    "#!python3.10 -m pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 torchtext==0.15.2 torchdata==0.6.1 --extra-index-url http://localhost:8000/ -U\n",
    "#!python3.10 -m pip install xformers==0.0.20 triton==2.0.0 -U\n",
    "#!python3.10 -m pip install httpx==0.24.1\n",
    "#!python3.10 -m pip install insightface -U\n",
    "#!python3.10 -m pip install matplotlib -U\n",
    "#!python3.10 -m pip install ipython -U\n",
    "\n",
    "!/storage/config/preparation.sh\n",
    "\n",
    "from IPython import get_ipython\n",
    "get_ipython().run_line_magic('matplotlib', 'inline')\n",
    "%cd /storage/stable-diffusion-webui\n",
    "!python3.10 launch.py --xformers --enable-insecure-extension-access --share --gradio-queue\n"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "private_outputs": true,
   "provenance": []
  },
  "gpuClass": "standard",
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
